config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "places#index"

  resources :places, only: :index do
    collection do
      get 'maps'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  PASSSWORD_REGEX = /\A(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]+\z/

  validates :password, format: { with: PASSSWORD_REGEX, message: 'は6文字以上で、半角英字と半角数字の両方を含めてください' }
  validates :nickname, presence: true

  # 管理者かどうかを判定するメソッド
  def admin?
    role == "admin"
  end
  # 一般ユーザーかどうかを判定するメソッド（オプション）
  def user?
    role == "user"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :role])
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
  end
  def maps
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkPlaceSearch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initAutocomplete&libraries=places&v=weekly" async></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/places/index.html.erb
<%= render "shared/header" %>

<!-- Services section -->
  <section id="services">
    <div class="container">
      <div class="row mb-4">
        <div class="col-md-8 mx-auto text-center">
          <h1>Services</h1>
          <p>
            今日はどこで仕事する？
          </p>
        </div>
      </div>
      <div class="row g-4">
        <div class="col-lg-12 col-sm-6">
          <div class="service card-effect ">
            <%= link_to '',  maps_places_path %>
            <div class="iconbox">
              <i class='bx bx-map'></i>
            </div>
            <h5 class="mt-4 mb-2">地図から探す</h5>
            <p>
              Google map上から今のあなたにピッタリな場所が探せます
            </p>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="service card-effect">
            <div class="iconbox">
              <i class='bx bx-area' ></i>
            </div>
            <h5 class="mt-4 mb-2">エリアから探す</h5>
            <p>
              都道府県、路線などのエリア検索します
            </p>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="service card-effect">
            <div class="iconbox">
              <i class='bx bxs-keyboard'></i>
            </div>
            <h5 class="mt-4 mb-2">キーワードで探す</h5>
            <p>
              キーワードでフリー検索します
            </p>
          </div>
        </div>
        <div class="col-lg-4 col-sm-6">
          <div class="service card-effect">
            <div class="iconbox">
              <i class='bx bx-search'></i>
            </div>
            <h5 class="mt-4 mb-2">特徴から探す</h5>
            <p>
              施設の特徴から探します
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>


<%= render "shared/footer" %>

app/views/places/maps.html.erb
<%= render "shared/header" %>

<h1 class= "text-center my-3" >地図から探す</h1>

  <input
      id="pac-input"
      class="controls"
      type="text"
      placeholder="Search Box"/>
  
  <div id="map"></div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-top">
    <div class="container">
      <div class="row gy-4">
        <div class="col-md-4">
          <h4 class="text-white">Workplace Search</h4>
        </div>
        <div class="col-md-2">
          <h5 class="text-white">Brand</h5>
          <ul class="list-unstyled">
            <li><a href="#">About</a></li>
            <li><a href="#">Services</a></li>
            <li><a href="#">Features</a></li>
            <li><a href="#">Pricing</a></li>
          </ul>
          </div>
        <div class="col-md-2">
          <h5 class="text-white">More</h5>
          <ul class="list-unstyled">
            <li><a href="#">FAQ&'s</a></li>
            <li><a href="#">Privacy & Policy</a></li>
            <li><a href="#">Warrantry</a></li>
            <li><a href="#">Shipment</a></li>
          </ul>
        </div>
        <div class="col-md-4">
          <h5 class="text-white">Pages</h5>
          <ul class="list-unstyled">
            <li>Address: Marunouchi, 1-9-1, Chiyoda-ku, Tokyo, Japan</li>
            <li>Email: test@gmail.com</li>
            <li>Phone: 111-222-333</li>
          </ul>
        </div>
      </div>
    </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark py-3 sticky-top">
      <div class="container">
        <a class="navbar-brand d-flex" href="/">
          <%= image_tag 'logo-only.png', class: "logo" %>
          <h2 class="ms-3 pt-2 text-white">Workplace Search</h2>
        </a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto ">
          <% if user_signed_in? %>
            <li class="nav-item p-2">
              <a class="nav-link" href="#home">Session</a>
            </li>
            <li class="nav-item p-2">
              <a class="nav-link" href="#services">レビュー投稿</a>
            </li>
            <li class="nav-item p-2">
              <a class="nav-link" href="#features">マイページ</a>
            </li>
            <li class= "navbar-user ms-4 my-auto "> ユーザー：<%= current_user.nickname %> </li> 
            <li ><%= link_to "ログアウト", destroy_user_session_path, class: "btn btn-danger ms-3", data: { turbo_method: :delete } %></li>
          <% else %>
          <li ><%= link_to 'ログイン', new_user_session_path, class: "btn btn-light ms-3" %></li>
          <li ><%= link_to '新規登録', new_user_registration_path, class: "btn btn-primary ms-3" %></li>
          <% end %>
          </ul>

        </div>
      </div>
    </nav>
</header>

app/views/shared/_second-footer.html.erb
<footer class="second-footer-top">
    <div class="container">
        <div class="col-md-12 mx-auto mb-5 text-center ">
          <h4 class="text-white">Workplace Search</h4>
        </div>
          <ul class="list-unstyled d-flex justify-content-end">
            <li class= "ms-3"><a href="#">利用規約</a></li>
            <li class= "ms-3"><a href="#">特定商取引法に基づく表示</a></li>
            <li class= "ms-3"><a href="#">コミュニティガイドライン</a></li>
            <li class= "ms-3"><a href="#">プライバシーポリシー</a></li>
          </ul>
    </div>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-top-page-header'>
  <div class="contener d-flex justify-content-center">
    <%= link_to image_tag("logo-only.png", class:"second-logo"), "/" %>
  </div>
</header>